# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Anvil < Formula
  desc "Portable Rust Agent Client Protocol (ACP) server with model routing"
  homepage "https://github.com/brokkai/anvil"
  version "0.24.2"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/anvil/releases/download/v0.24.2/brokk-anvil-v0.24.2-universal-apple-darwin.zip"
    sha256 "2c6f1f4331903fdabcd9fc0dca80abe9e371d23c71f1597491683993acc631e2"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/anvil/releases/download/v0.24.2/brokk-anvil-v0.24.2-x86_64-unknown-linux-gnu.zip"
      sha256 "f4675f7bf50e3fc84be6de6569461d55451cf0a78fad5e36b6b84e32d9bf5378"
    end
    on_arm do
      url "https://github.com/brokkai/anvil/releases/download/v0.24.2/brokk-anvil-v0.24.2-aarch64-unknown-linux-gnu.zip"
      sha256 "e18cb286addd7d1920025c3b5dbd501c447dcfa146d4c480e19135d810bcf736"
    end
  end

  def install
    bin.install "anvil"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anvil --version")
  end
end
