# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Anvil < Formula
  desc "Portable Rust Agent Client Protocol (ACP) server with model routing"
  homepage "https://github.com/brokkai/anvil"
  version "0.25.0"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/anvil/releases/download/v0.25.0/brokk-anvil-v0.25.0-universal-apple-darwin.zip"
    sha256 "e2a1b948dc9a2e1a9c654751e42df15b0f403f87bfad6863db5d68b40869f510"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/anvil/releases/download/v0.25.0/brokk-anvil-v0.25.0-x86_64-unknown-linux-gnu.zip"
      sha256 "96c152d0bdca4d6739c8ce59c90db702c4965f7ffb0b051aae77d2b5765ae9ba"
    end
    on_arm do
      url "https://github.com/brokkai/anvil/releases/download/v0.25.0/brokk-anvil-v0.25.0-aarch64-unknown-linux-gnu.zip"
      sha256 "7d1e6453f8ea38637393978fcadb4e1f7bc9216ff1bf44c40acdbfe58d3df05d"
    end
  end

  def install
    bin.install "anvil"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anvil --version")
  end
end
