# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Bifrost < Formula
  desc "Multi-language static analysis for agents, editors, and large repos"
  homepage "https://github.com/brokkai/bifrost"
  version "0.10.9"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/bifrost/releases/download/v0.10.9/bifrost-v0.10.9-universal-apple-darwin.tar.gz"
    sha256 "69ae168ae8fb3a96046360b8796343ec124fc720b9e089f98a35133f3a260a96"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/bifrost/releases/download/v0.10.9/bifrost-v0.10.9-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "5d38b979aae45643ff3fdb91273cb06f1938c2ce2abb09ae9bcc725f2b025d07"
    end
    on_arm do
      url "https://github.com/brokkai/bifrost/releases/download/v0.10.9/bifrost-v0.10.9-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "8fb98cd623592422e329b0110100f34e1836705c5caf0017ce58d0274fd21380"
    end
  end

  def install
    bin.install "bifrost"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bifrost --version")
  end
end
