# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Bifrost < Formula
  desc "Multi-language static analysis for agents, editors, and large repos"
  homepage "https://github.com/brokkai/bifrost"
  version "0.10.1"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/bifrost/releases/download/v0.10.1/bifrost-v0.10.1-universal-apple-darwin.tar.gz"
    sha256 "20ccf21e5882cf1c828f8b51da93adf86f128d50ef12108d59eed5694c163721"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/bifrost/releases/download/v0.10.1/bifrost-v0.10.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ccf18aa960e23751be74bd4bcf77e1417887d94a644c25956ca490a62a7b1083"
    end
    on_arm do
      url "https://github.com/brokkai/bifrost/releases/download/v0.10.1/bifrost-v0.10.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "67ad9cd564aa7742a71f82a42565a09206db865181cbeee3068ea71ec9aba971"
    end
  end

  def install
    bin.install "bifrost"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bifrost --version")
  end
end
