# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Bifrost < Formula
  desc "Multi-language static analysis for agents, editors, and large repos"
  homepage "https://github.com/brokkai/bifrost"
  version "0.11.3"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/bifrost/releases/download/v0.11.3/bifrost-v0.11.3-universal-apple-darwin.tar.gz"
    sha256 "c1d18545bc301ad1b5a7604298fbdaf67aba82d1c78a466a6919038e5c2a45c9"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/bifrost/releases/download/v0.11.3/bifrost-v0.11.3-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "6ff3f146f13c9f773f6d90e6f778b971717b01bca88b5dbe97f3075aade4354e"
    end
    on_arm do
      url "https://github.com/brokkai/bifrost/releases/download/v0.11.3/bifrost-v0.11.3-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "e96f6f6a80c514f9bc57f0d3f4effcc7ee280a77a70d495303fc82d4e1cc6b7d"
    end
  end

  def install
    bin.install "bifrost"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bifrost --version")
  end
end
