# Generated by scripts/update-formulae.sh -- do not edit by hand.
class BrokkTown < Formula
  desc "Local town of coordinated repository agents, with a browser and CLI"
  homepage "https://github.com/brokkai/brokk-town"
  version "0.9.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/brokkai/brokk-town/releases/download/v0.9.0/brokk-town_v0.9.0_darwin_amd64.tar.gz"
      sha256 "6c41abd6d258a722de6b6eadfcff18ceb6a1baee61201b7e102b3ab07ed06219"
    end
    on_arm do
      url "https://github.com/brokkai/brokk-town/releases/download/v0.9.0/brokk-town_v0.9.0_darwin_arm64.tar.gz"
      sha256 "0e22fdd473a104b94f6541f97ae6ebf601bf2c7135d21186ba4a97fae93d6109"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/brokk-town/releases/download/v0.9.0/brokk-town_v0.9.0_linux_amd64.tar.gz"
      sha256 "28f5608fff85db98a76281c8ffba4dfac5be1526bc24e2857614998582d57330"
    end
    on_arm do
      url "https://github.com/brokkai/brokk-town/releases/download/v0.9.0/brokk-town_v0.9.0_linux_arm64.tar.gz"
      sha256 "f98147a9fbde4e14510e78701dc6048a9cd5732eee04f51f2f7a6ede7a07fada"
    end
  end

  def install
    bin.install "bt"
    doc.install Dir["LICENSE*", "NOTICE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bt version")
  end
end
