# Generated by scripts/update-formulae.sh -- do not edit by hand.
class MicroAcp < Formula
  desc "Go terminal client for the Agent Client Protocol (ACP)"
  homepage "https://github.com/brokkai/micro-acp"
  version "0.6.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.6.0/micro-acp_0.6.0_darwin_amd64.tar.gz"
      sha256 "259bedc22011460f95cd9abfd43dc4e111a7267052c0113164d62003b40f1be3"
    end
    on_arm do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.6.0/micro-acp_0.6.0_darwin_arm64.tar.gz"
      sha256 "b5b3a76d2c01fe76415902583536d2038aa8c2fe0ffeb5c38adba8cada6ba3ce"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.6.0/micro-acp_0.6.0_linux_amd64.tar.gz"
      sha256 "8795848093c1a384a9e6de5a10e0c5356d733fba171621d79e33af94d1da53ba"
    end
    on_arm do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.6.0/micro-acp_0.6.0_linux_arm64.tar.gz"
      sha256 "aa0a5587027c092ba259820f9fbaa54064dc256d95a823536a4c33504a700776"
    end
  end

  def install
    bin.install "micro-acp"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/micro-acp --version")
  end
end
