# Generated by scripts/update-formulae.sh -- do not edit by hand.
class MicroAcp < Formula
  desc "Go terminal client for the Agent Client Protocol (ACP)"
  homepage "https://github.com/brokkai/micro-acp"
  version "0.7.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.7.0/micro-acp_0.7.0_darwin_amd64.tar.gz"
      sha256 "906199116860ca702c57cdbf161adc07d803f37aea1a39776d76722ea50085bf"
    end
    on_arm do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.7.0/micro-acp_0.7.0_darwin_arm64.tar.gz"
      sha256 "07f22cf5e360ffc74368c7e5cbf7a1eecf3155dcd5dbb8d9a02c3564e114cc40"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.7.0/micro-acp_0.7.0_linux_amd64.tar.gz"
      sha256 "c8b213ce4d7dcce65ecd202200ffc6e5423d0c2918dd192f925d1d0ea0e2dbcb"
    end
    on_arm do
      url "https://github.com/brokkai/micro-acp/releases/download/v0.7.0/micro-acp_0.7.0_linux_arm64.tar.gz"
      sha256 "5db7c5992b30562220c3c22d0c3978961af0c594d456ccefb62e468d64cf47b9"
    end
  end

  def install
    bin.install "micro-acp"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/micro-acp --version")
  end
end
