# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Mjolnir < Formula
  desc "Rust terminal client for Agent Client Protocol (ACP) coding agents"
  homepage "https://github.com/brokkai/mjolnir"
  version "2.3.1"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/mjolnir/releases/download/v2.3.1/brokk-mjolnir-v2.3.1-universal-apple-darwin.tar.gz"
    sha256 "d09bfec2a7c543efce21ef2244c3bd36073b2f13dc51a17d225d5f3447eeb65c"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/mjolnir/releases/download/v2.3.1/brokk-mjolnir-v2.3.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "59f1d905e8490e8d6d9f0e14bbfb7666d49fbcf0ddc9d7418da9021f6ee8232d"
    end
    on_arm do
      url "https://github.com/brokkai/mjolnir/releases/download/v2.3.1/brokk-mjolnir-v2.3.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c1a1f40e812171d534ab096c85d3bd3ae0bb44fb1162e41e084b639d8534633c"
    end
  end

  # mj ships helper binaries (mj-voice-worker and a bundled anvil) that must
  # live next to it, so everything stays in libexec and only mj is exposed.
  # This also avoids colliding with the standalone anvil formula.
  # Homebrew owns this installation, so mj's own startup update check is
  # disabled; updates arrive through brew upgrade. The value must be "true",
  # not "1": clap parses the env value strictly as a boolean.
  def install
    libexec.install Dir["*"]
    (bin/"mj").write_env_script libexec/"mj", MJOLNIR_NO_UPDATE_CHECK: "true"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mj --version")
  end
end
