# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Mjolnir < Formula
  desc "Rust terminal client for Agent Client Protocol (ACP) coding agents"
  homepage "https://github.com/brokkai/mjolnir"
  version "1.13.2"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/mjolnir/releases/download/v1.13.2/brokk-mjolnir-v1.13.2-universal-apple-darwin.tar.gz"
    sha256 "87911d630fdd2ed5dc937ca5d65fe08e2d9ec59234ae78ee754f1aa73d4c7603"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/mjolnir/releases/download/v1.13.2/brokk-mjolnir-v1.13.2-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2742b4471fbb251f466c830e94b7de1edbf00be0bdc3469e3eaa02618ccdb7c1"
    end
    on_arm do
      url "https://github.com/brokkai/mjolnir/releases/download/v1.13.2/brokk-mjolnir-v1.13.2-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "709402f0bdcd0fb86feaff5464dd29ccd936f0f7cec250a4a619dd8638799dd5"
    end
  end

  # mj ships helper binaries (mj-voice-worker and a bundled anvil) that must
  # live next to it, so everything stays in libexec and only mj is exposed.
  # This also avoids colliding with the standalone anvil formula.
  # Homebrew owns this installation, so mj's own startup update check is
  # disabled; updates arrive through brew upgrade. The value must be "true",
  # not "1": clap parses the env value strictly as a boolean.
  def install
    libexec.install Dir["*"]
    (bin/"mj").write_env_script libexec/"mj", MJOLNIR_NO_UPDATE_CHECK: "true"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mj --version")
  end
end
