# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Mjolnir < Formula
  desc "Rust terminal client for Agent Client Protocol (ACP) coding agents"
  homepage "https://github.com/brokkai/mjolnir"
  version "1.11.1"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/mjolnir/releases/download/v1.11.1/brokk-mjolnir-v1.11.1-universal-apple-darwin.tar.gz"
    sha256 "0fcf8fb866c1b5349ef2a4d0822611322fc8e20461fbef197b838d69c3c0d565"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/mjolnir/releases/download/v1.11.1/brokk-mjolnir-v1.11.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "12333dfddc9367d9a38cc7de8484b228a21b503266aa1f40df583d39b218f356"
    end
    on_arm do
      url "https://github.com/brokkai/mjolnir/releases/download/v1.11.1/brokk-mjolnir-v1.11.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0cca074cb5205ed06d1bdb08878833adc04ea10eef14cd714bef57f1c2f42565"
    end
  end

  # mj ships helper binaries (mj-voice-worker and a bundled anvil) that must
  # live next to it, so everything stays in libexec and only mj is exposed.
  # This also avoids colliding with the standalone anvil formula.
  # Homebrew owns this installation, so mj's own startup update check is
  # disabled; updates arrive through brew upgrade. The value must be "true",
  # not "1": clap parses the env value strictly as a boolean.
  def install
    libexec.install Dir["*"]
    (bin/"mj").write_env_script libexec/"mj", MJOLNIR_NO_UPDATE_CHECK: "true"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mj --version")
  end
end
