#!/usr/bin/env bash
# Regenerates Formula/*.rb from the latest GitHub releases of each tool.
# Checksums are taken from the .sha256 files published alongside each
# release asset, so this script never computes hashes itself.
#
# Requires: gh (authenticated, or GH_TOKEN set), curl.
set -euo pipefail

cd "$(dirname "$0")/.."
mkdir -p Formula

ORG=brokkai

latest_version() {
  gh api "repos/$ORG/$1/releases/latest" --jq '.tag_name' | sed 's/^v//'
}

asset_sha256() {
  local repo=$1 asset=$2
  curl -fsSL --retry 3 \
    "https://github.com/$ORG/$repo/releases/download/v$3/$asset.sha256" | awk '{print $1}'
}

generate_mjolnir() {
  local v mac linux_x86 linux_arm
  v=$(latest_version mjolnir)
  mac=$(asset_sha256 mjolnir "brokk-mjolnir-v$v-universal-apple-darwin.tar.gz" "$v")
  linux_x86=$(asset_sha256 mjolnir "brokk-mjolnir-v$v-x86_64-unknown-linux-gnu.tar.gz" "$v")
  linux_arm=$(asset_sha256 mjolnir "brokk-mjolnir-v$v-aarch64-unknown-linux-gnu.tar.gz" "$v")

  cat > Formula/mjolnir.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Mjolnir < Formula
  desc "Rust terminal client for Agent Client Protocol (ACP) coding agents"
  homepage "https://github.com/brokkai/mjolnir"
  version "$v"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/mjolnir/releases/download/v$v/brokk-mjolnir-v$v-universal-apple-darwin.tar.gz"
    sha256 "$mac"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/mjolnir/releases/download/v$v/brokk-mjolnir-v$v-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/mjolnir/releases/download/v$v/brokk-mjolnir-v$v-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
  end

  # mj ships helper binaries (mj-voice-worker and a bundled anvil) that must
  # live next to it, so everything stays in libexec and only mj is exposed.
  # This also avoids colliding with the standalone anvil formula.
  def install
    libexec.install Dir["*"]
    bin.write_exec_script libexec/"mj"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mj --version")
  end
end
EOF
  echo "mjolnir $v"
}

generate_anvil() {
  local v mac linux_x86 linux_arm
  v=$(latest_version anvil)
  mac=$(asset_sha256 anvil "brokk-anvil-v$v-universal-apple-darwin.zip" "$v")
  linux_x86=$(asset_sha256 anvil "brokk-anvil-v$v-x86_64-unknown-linux-gnu.zip" "$v")
  linux_arm=$(asset_sha256 anvil "brokk-anvil-v$v-aarch64-unknown-linux-gnu.zip" "$v")

  cat > Formula/anvil.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Anvil < Formula
  desc "Portable Rust Agent Client Protocol (ACP) server with model routing"
  homepage "https://github.com/brokkai/anvil"
  version "$v"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/anvil/releases/download/v$v/brokk-anvil-v$v-universal-apple-darwin.zip"
    sha256 "$mac"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/anvil/releases/download/v$v/brokk-anvil-v$v-x86_64-unknown-linux-gnu.zip"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/anvil/releases/download/v$v/brokk-anvil-v$v-aarch64-unknown-linux-gnu.zip"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "anvil"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anvil --version")
  end
end
EOF
  echo "anvil $v"
}

generate_bifrost() {
  local v mac linux_x86 linux_arm
  v=$(latest_version bifrost)
  mac=$(asset_sha256 bifrost "bifrost-v$v-universal-apple-darwin.tar.gz" "$v")
  linux_x86=$(asset_sha256 bifrost "bifrost-v$v-x86_64-unknown-linux-gnu.tar.gz" "$v")
  linux_arm=$(asset_sha256 bifrost "bifrost-v$v-aarch64-unknown-linux-gnu.tar.gz" "$v")

  cat > Formula/bifrost.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Bifrost < Formula
  desc "Multi-language static analysis for agents, editors, and large repos"
  homepage "https://github.com/brokkai/bifrost"
  version "$v"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/bifrost/releases/download/v$v/bifrost-v$v-universal-apple-darwin.tar.gz"
    sha256 "$mac"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/bifrost/releases/download/v$v/bifrost-v$v-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/bifrost/releases/download/v$v/bifrost-v$v-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "bifrost"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"]
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bifrost --version")
  end
end
EOF
  echo "bifrost $v"
}

generate_mjolnir
generate_anvil
generate_bifrost
