#!/usr/bin/env bash
# Regenerates Formula/*.rb from the latest GitHub releases of each tool.
# Checksums are taken from the .sha256 files published alongside each
# release asset, so this script never computes hashes itself.
#
# Requires: gh (authenticated, or GH_TOKEN set), curl.
set -euo pipefail

cd "$(dirname "$0")/.."
mkdir -p Formula

ORG=brokkai

latest_version() {
  gh api "repos/$ORG/$1/releases/latest" --jq '.tag_name' | sed 's/^v//'
}

asset_sha256() {
  local repo=$1 asset=$2
  curl -fsSL --retry 3 \
    "https://github.com/$ORG/$repo/releases/download/v$3/$asset.sha256" | awk '{print $1}'
}

# micro-acp publishes a single checksums.txt alongside its release assets
# instead of one .sha256 file per asset.
checksums_txt_sha256() {
  local repo=$1 tag=$2 asset=$3
  curl -fsSL --retry 3 \
    "https://github.com/$ORG/$repo/releases/download/$tag/checksums.txt" |
    awk -v a="$asset" '$2 == a {print $1}'
}

generate_mjolnir() {
  local v mac linux_x86 linux_arm
  v=$(latest_version mjolnir)
  mac=$(asset_sha256 mjolnir "brokk-mjolnir-v$v-universal-apple-darwin.tar.gz" "$v")
  linux_x86=$(asset_sha256 mjolnir "brokk-mjolnir-v$v-x86_64-unknown-linux-gnu.tar.gz" "$v")
  linux_arm=$(asset_sha256 mjolnir "brokk-mjolnir-v$v-aarch64-unknown-linux-gnu.tar.gz" "$v")

  cat > Formula/mjolnir.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Mjolnir < Formula
  desc "Rust terminal client for Agent Client Protocol (ACP) coding agents"
  homepage "https://github.com/brokkai/mjolnir"
  version "$v"
  license "GPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/mjolnir/releases/download/v$v/brokk-mjolnir-v$v-universal-apple-darwin.tar.gz"
    sha256 "$mac"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/mjolnir/releases/download/v$v/brokk-mjolnir-v$v-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/mjolnir/releases/download/v$v/brokk-mjolnir-v$v-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
  end

  # mj ships helper binaries (mj-voice-worker and a bundled anvil) that must
  # live next to it, so everything stays in libexec and only mj is exposed.
  # This also avoids colliding with the standalone anvil formula.
  # Homebrew owns this installation: this marker tells mj's startup update
  # check to delegate to brew update and brew upgrade mjolnir after asking,
  # never to replace files inside the Cellar itself.
  def install
    libexec.install Dir["*"]
    (bin/"mj").write_env_script libexec/"mj", MJOLNIR_MANAGED_BY_HOMEBREW: "true"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/mj --version")
  end
end
EOF
  echo "mjolnir $v"
}

generate_anvil() {
  local v mac linux_x86 linux_arm
  v=$(latest_version anvil)
  mac=$(asset_sha256 anvil "brokk-anvil-v$v-universal-apple-darwin.zip" "$v")
  linux_x86=$(asset_sha256 anvil "brokk-anvil-v$v-x86_64-unknown-linux-gnu.zip" "$v")
  linux_arm=$(asset_sha256 anvil "brokk-anvil-v$v-aarch64-unknown-linux-gnu.zip" "$v")

  cat > Formula/anvil.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Anvil < Formula
  desc "Portable Rust Agent Client Protocol (ACP) server with model routing"
  homepage "https://github.com/brokkai/anvil"
  version "$v"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/anvil/releases/download/v$v/brokk-anvil-v$v-universal-apple-darwin.zip"
    sha256 "$mac"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/anvil/releases/download/v$v/brokk-anvil-v$v-x86_64-unknown-linux-gnu.zip"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/anvil/releases/download/v$v/brokk-anvil-v$v-aarch64-unknown-linux-gnu.zip"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "anvil"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/anvil --version")
  end
end
EOF
  echo "anvil $v"
}

generate_bifrost() {
  local v mac linux_x86 linux_arm
  v=$(latest_version bifrost)
  mac=$(asset_sha256 bifrost "bifrost-v$v-universal-apple-darwin.tar.gz" "$v")
  linux_x86=$(asset_sha256 bifrost "bifrost-v$v-x86_64-unknown-linux-gnu.tar.gz" "$v")
  linux_arm=$(asset_sha256 bifrost "bifrost-v$v-aarch64-unknown-linux-gnu.tar.gz" "$v")

  cat > Formula/bifrost.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class Bifrost < Formula
  desc "Multi-language static analysis for agents, editors, and large repos"
  homepage "https://github.com/brokkai/bifrost"
  version "$v"
  license "LGPL-3.0-only"

  on_macos do
    url "https://github.com/brokkai/bifrost/releases/download/v$v/bifrost-v$v-universal-apple-darwin.tar.gz"
    sha256 "$mac"
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/bifrost/releases/download/v$v/bifrost-v$v-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/bifrost/releases/download/v$v/bifrost-v$v-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "bifrost"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bifrost --version")
  end
end
EOF
  echo "bifrost $v"
}

generate_micro_acp() {
  local tag v mac_x86 mac_arm linux_x86 linux_arm
  tag=$(gh api "repos/$ORG/micro-acp/releases/latest" --jq '.tag_name')
  v=${tag#v}
  mac_x86=$(checksums_txt_sha256 micro-acp "$tag" "micro-acp_${v}_darwin_amd64.tar.gz")
  mac_arm=$(checksums_txt_sha256 micro-acp "$tag" "micro-acp_${v}_darwin_arm64.tar.gz")
  linux_x86=$(checksums_txt_sha256 micro-acp "$tag" "micro-acp_${v}_linux_amd64.tar.gz")
  linux_arm=$(checksums_txt_sha256 micro-acp "$tag" "micro-acp_${v}_linux_arm64.tar.gz")

  cat > Formula/micro-acp.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class MicroAcp < Formula
  desc "Go terminal client for the Agent Client Protocol (ACP)"
  homepage "https://github.com/brokkai/micro-acp"
  version "$v"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/brokkai/micro-acp/releases/download/$tag/micro-acp_${v}_darwin_amd64.tar.gz"
      sha256 "$mac_x86"
    end
    on_arm do
      url "https://github.com/brokkai/micro-acp/releases/download/$tag/micro-acp_${v}_darwin_arm64.tar.gz"
      sha256 "$mac_arm"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/micro-acp/releases/download/$tag/micro-acp_${v}_linux_amd64.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/micro-acp/releases/download/$tag/micro-acp_${v}_linux_arm64.tar.gz"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "micro-acp"
    doc.install Dir["LICENSE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/micro-acp --version")
  end
end
EOF
  echo "micro-acp $v"
}

generate_brokk_town() {
  local tag v mac_x86 mac_arm linux_x86 linux_arm
  tag=$(gh api "repos/$ORG/brokk-town/releases/latest" --jq '.tag_name')
  v=${tag#v}
  mac_x86=$(checksums_txt_sha256 brokk-town "$tag" "brokk-town_${tag}_darwin_amd64.tar.gz")
  mac_arm=$(checksums_txt_sha256 brokk-town "$tag" "brokk-town_${tag}_darwin_arm64.tar.gz")
  linux_x86=$(checksums_txt_sha256 brokk-town "$tag" "brokk-town_${tag}_linux_amd64.tar.gz")
  linux_arm=$(checksums_txt_sha256 brokk-town "$tag" "brokk-town_${tag}_linux_arm64.tar.gz")

  cat > Formula/brokk-town.rb <<EOF
# Generated by scripts/update-formulae.sh -- do not edit by hand.
class BrokkTown < Formula
  desc "Local town of coordinated repository agents, with a browser and CLI"
  homepage "https://github.com/brokkai/brokk-town"
  version "$v"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/brokkai/brokk-town/releases/download/$tag/brokk-town_${tag}_darwin_amd64.tar.gz"
      sha256 "$mac_x86"
    end
    on_arm do
      url "https://github.com/brokkai/brokk-town/releases/download/$tag/brokk-town_${tag}_darwin_arm64.tar.gz"
      sha256 "$mac_arm"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brokkai/brokk-town/releases/download/$tag/brokk-town_${tag}_linux_amd64.tar.gz"
      sha256 "$linux_x86"
    end
    on_arm do
      url "https://github.com/brokkai/brokk-town/releases/download/$tag/brokk-town_${tag}_linux_arm64.tar.gz"
      sha256 "$linux_arm"
    end
  end

  def install
    bin.install "bt"
    doc.install Dir["LICENSE*", "NOTICE*", "*.md", "*.html", "*.txt"].uniq
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/bt version")
  end
end
EOF
  echo "brokk-town $v"
}

generate_mjolnir
generate_anvil
generate_bifrost
generate_micro_acp
generate_brokk_town
